### ISSUE TITLE
Update JSON file

### ISSUE THREAD

**Issue by antondozortsev** [crowdin/crowdin-java-sdk#8]
Hey Ihor (@ihorpopyk @ihor-popyk),

Could you please show example on Java code of how to update JSON file using crowdin-java-sdk library.

My JSON file looks like below:

```json
{
  "country.and":"Andorra",
  "country.gbr":"United Kingdom",
  "country.usa":"United States",
  "country.bel":"Belgium"
}
```
and I need add one line there: `"country.ee": "Estonia"`

```java
CrowdinApiClient client = new Crwdn();
final Credentials credentials = new Credentials(
        BASE_URL, PROJECT_IDENTIFIER, PROJECT_KEY, ACCOUNT_KEY
);
CrowdinApiParametersBuilder parametersBuilder = new CrowdinApiParametersBuilder();
parametersBuilder.file("angular.json");
// where should I put new row ??
parametersBuilder.language("ru");
ClientResponse response = client.updateFile(credentials, parametersBuilder);
```

Thanks

**Comment by ihor-popyk** [comment]
Hello @antondozortsev 
You just need to add new line to your file (e.g. angular.json) and update all file.
`CrowdinApiClient client = new Crwdn();
final Credentials credentials = new Credentials( BASE_URL, PROJECT_IDENTIFIER, PROJECT_KEY, ACCOUNT_KEY);
CrowdinApiParametersBuilder parametersBuilder = new CrowdinApiParametersBuilder();
parametersBuilder.files("PATH_TO_FILE");
parametersBuilder.titles("PATH_TO_FILE", "PATH_IN_CROWDIN");
ClientResponse response = client.updateFile(credentials, parametersBuilder);`

**Comment by antondozortsev** [comment]
@ihor-popyk Got it, thanks for answer.

I thought that I can modify JSON file by add new line trough Crowdin REST API to project which is registered in Crowdin.

**Comment by ihor-popyk** [comment]
@antondozortsev ,
you are welcome :)
